#!/bin/sh

LIBS="-lintl" ./configure --disable-dependency-tracking --prefix=`pwd`"/Toppler.app/Contents/Resources/toppler" --exec-prefix=`pwd`"/Toppler.app/Contents/MacOS" --bindir=`pwd`"/Toppler.app/Contents/MacOS"
