#!/bin/sh

FLAGS="-arch i386 -mmacosx-version-min=10.7" 

CXXFLAGS="${FLAGS}" CPPFLAGS="${FLAGS}" CFLAGS="${FLAGS}" LDFLAGS="${FLAGS}" LIBS="-lintl" ./configure --disable-dependency-tracking --prefix=`pwd`"/Toppler.app/Contents/Resources/toppler" --exec-prefix=`pwd`"/Toppler.app/Contents/MacOS" --bindir=`pwd`"/Toppler.app/Contents/MacOS" --with-sdl-prefix=$HOME/projects/root
